Auction/Models/CreateLotViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Auction.DAL.Entities;
using Auction.Validation;

namespace Auction.Models
{
    public class CreateLotViewModel
    {
        [Required]
        [Display(Name = "Lot's name")]
        public string Name { get; set; }
        
        [Display(Name = "Prime bet's sum")]
        [Required]
        [Range(0, 10_000, ErrorMessage = "Prime bet must be in range from 0 to 10 000")]
        public decimal PrimeBetPrice { get; set; }
        
        [Display(Name = "Finishing date")]        
        [LotData]
        [Required(ErrorMessage = "Select valid date.")]
        public DateTime FinishingDate { get; set; }
        
        [Required]
        public CreateCoinViewModel Coin { get; set; }
        
        public string Description { get; set; }
    }
}

Auction/Models/EditLotViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Auction.Models
{
    public class EditLotViewModel
    {
        [Required]
        [Display(Name = "Lot's name")]
        public string Name { get; set; }

        [Required]
        public CreateCoinViewModel Coin { get; set; }
        
        public string Description { get; set; }
        
        public string ReturnUrl { get; set; }
    }
}

Auction/Controllers/BetController.cs
using System;
using Auction.BLL.Interfaces;
using Auction.DAL.Entities;
using Auction.Infrastructure;
using Auction.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Auction.Controllers
{
    public class BetController : Controller
    {
        private readonly ILotService lotService;
        private readonly IBetService betService;
        private readonly IUserService userService;

        public BetController(ILotService lotService, IBetService betService, IUserService userService)
        {
            this.lotService = lotService;
            this.betService = betService;
            this.userService = userService;
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateBet(int lotId, decimal sum)
        {
            try
            {
                string userId = userService.GetUserId(this.User);
                Lot lot = lotService.GetLot(lotId);

                if (!lotService.IsLotActive(lotId))
                {
                    throw new NonActiveLotException(lot.Name);
                }

                if (userId == lot.UserId)
                {
                    throw new ArgumentException("Owner can't make bets on this lot.");
                }

                betService.CreateBet(userId, lotId, sum);
                lotService.ChangeActualPrice(lotId, sum);

                return RedirectToAction("ViewLot", "Home",new {lotId});
            }
            catch (ArgumentNullException e)
            {
                return View("Error", new ErrorViewModel
                {
                    ErrorMessage = e.Message + " Parameter " + e.ParamName + " is undefined."
                });
            }
            catch (ArgumentException e)
            {
                return View("Error", new ErrorViewModel
                {
                    ErrorMessage = e.Message
                });
            }
            catch (NonActiveLotException e)
            {
                return View("Error", new ErrorViewModel
                {
                    ErrorMessage = e.LotName + " isn't active. Please, find other liked lot."
                });
            }
        }
    }
}

Auction/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Auction.BLL.Interfaces;
using Auction.BLL.Services;
using Auction.DAL.Entities;
using Microsoft.AspNetCore.Mvc;
using Auction.Models;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Auction.Controllers
{
    public class HomeController : Controller
    {
        private readonly IWebHostEnvironment appEnvironment;
        private readonly ILotService lotService;
        private readonly IUserService userService;
        private readonly IMapper mapper;
        
        public HomeController(IWebHostEnvironment appEnvironment, IMapper mapper,
            ILotService lotService, IUserService userService)
        {
            this.appEnvironment = appEnvironment;
            this.lotService = lotService;
            this.userService = userService;
            this.mapper = mapper;
        }

        public async Task<IActionResult> Index(string searchingString)
        {
            List<Lot> lots = !string.IsNullOrEmpty(searchingString) ? 
                lotService.GetActiveLots(searchingString) : lotService.GetActiveLots();
            List<LotViewModel> lotViewModels = mapper.Map<List<Lot>, List<LotViewModel>>(lots);

            for (int i = 0; i < lots.Count; i++)
            {
                var user = await userService.GetUserById(lots[i].UserId);
                string directoryName = appEnvironment.WebRootPath + @"\img\lotsimages";
                string pattern = directoryName + @"\" + user.Id + "_" + lots[i].LotId + "_";

                LotImagesLoader loader = new LotImagesLoader();
                var images = loader.FindImages(directoryName, pattern);

                lotViewModels[i].Coin.Images = images.Any() ? images : null;
            }
            
            return View(lotViewModels);
        }

        [HttpGet]
        [Authorize]
        public IActionResult CreateLot()
        {
            ViewBag.Metals = new SelectList(Enum.GetNames(typeof(Metal)));
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateLot(CreateLotViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ViewBag.Metals = new SelectList(Enum.GetNames(typeof(Metal)));
                    return View();
                }

                if (model is null)
                {
                    throw new ArgumentNullException(nameof(model), "Impossible to create lot, invalid data for lot.");
                }
                
                string userId = userService.GetUserId(this.User);
                Lot lot = mapper.Map<Lot>(model);
                lot.UserId = userId;
                lotService.CreateLot(lot);
                await WriteImages(model.Coin.Images, userId, lot.LotId);
                
                return RedirectToAction("ViewLot", new {lotId = lot.LotId});
            }
            catch (ArgumentNullException e)
            {
                return View("Error", new ErrorViewModel
                {
                    ErrorMessage = e.Message + " Parameter " + e.ParamName + " is undefined."

                });
            }
        }

        [NonAction]
        private async Task WriteImages(IEnumerable<IFormFile> images, string userId, int lotId)
        {
            if (images is { })
            {
                foreach(var image in images)
                {
                    string path =  appEnvironment.WebRootPath + @"\img\lotsimages" + @"\" + userId + "_" + lotId + "_" + Guid.NewGuid().ToString() + "_" + image.FileName;

                    await using var fileStream = new FileStream(path, FileMode.Create);
                    await image.CopyToAsync(fileStream);
                }
            }
        }

        [HttpGet]
        public async Task<IActionResult> ViewLot(int lotId)
        {
            try
            { 
                Lot lot = lotService.GetLot(lotId);

                var user = await userService.GetUserById(lot.UserId);
                
                string directoryName = appEnvironment.WebRootPath + @"\img\lotsimages";
                string pattern = directoryName + @"\" + user.Id + "_" + lotId + "_";

                LotImagesLoader loader = new LotImagesLoader();
                IEnumerable<string> images = loader.FindImages(directoryName, pattern);
                
                var lotViewModel = mapper.Map<LotViewModel>(lot);
                lotViewModel.UserName = user.UserName;
                lotViewModel.Coin.Images =  images.Any() ? images : null;
                lotViewModel.Phone = user.PhoneNumber;
                ViewBag.OwnerId = user.Id;

                return View(lotViewModel);
            }
            catch (ArgumentNullException e)
            {
                return View("Error", new ErrorViewModel
                {
                    ErrorMessage = e.Message + " Parameter " + e.ParamName + " is undefined."

                });
            }
            catch (ArgumentException e)
            {
                return View("Error", new ErrorViewModel
                {
                    ErrorMessage = e.Message
                });
            }
        }

        [Authorize]
        [HttpPost]
        public IActionResult DeleteLot(int lotId)
        {
            try
            {
                string userId = userService.GetUserId(this.User);
                
                lotService.DeleteLot(lotId, userId);

                string directoryName = appEnvironment.WebRootPath + @"\img\lotsimages";
                string pattern = directoryName + @"\" + userId + "_" + lotId + "_";

                LotImagesRemover remover = new LotImagesRemover();
                remover.FindAndRemoveImages(directoryName, pattern);
                
                return View("LotSuccessfullyDeleted");
            }
            catch (ArgumentNullException e)
            {
                return View("Error", new ErrorViewModel
                {
                    ErrorMessage = e.Message + " Parameter " + e.ParamName + " is undefined."
                });
            }
            catch (ArgumentException e)
            {
                return View("Error", new ErrorViewModel
                {
                    ErrorMessage = e.Message
                });
            }
        }

        [Authorize]
        [HttpGet]
        public IActionResult EditLot(int lotId)
        {
            try
            {
                Lot lot = lotService.GetLot(lotId);
                string userId = userService.GetUserId(this.User);

                if (lot.UserId != userId)
                {
                    throw new ArgumentException("Impossible to edit lot. You are not an owner of it.");
                }
                
                ViewBag.Metals = new SelectList(Enum.GetNames(typeof(Metal)));
                ViewBag.lotId = lotId;

                var editLotViewModel = mapper.Map<EditLotViewModel>(lot);
                
                return View(editLotViewModel);
            }
            catch (ArgumentNullException e)
            {
                return View("Error", new ErrorViewModel
                {
                    ErrorMessage = e.Message + " Parameter " + e.ParamName + " is undefined."
                });
            }
            catch (ArgumentException e)
            {
                return View("Error", new ErrorViewModel
                {
                    ErrorMessage = e.Message
                });
            }
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EditLot(EditLotViewModel model, int lotId)
        {
            Lot lot = lotService.GetLot(lotId);
            string userId = userService.GetUserId(this.User);
            
            if (!ModelState.IsValid || model is null || model.Coin is null || lot.UserId != userId)
            {
                return View("Error");
            }
            
            lot.Coin = mapper.Map<Coin>(model.Coin);
            
            lot.Description = model.Description;

            if (model.Coin.Images is { })
            {
                string directoryName = appEnvironment.WebRootPath + @"\img\lotsimages";
                string pattern = directoryName + @"\" + userId + "_" + lotId + "_";
                
                LotImagesRemover remover = new LotImagesRemover();
                remover.FindAndRemoveImages(directoryName, pattern);

                await WriteImages(model.Coin.Images, userId, lotId);
            }
            
            lotService.EditLot(lot);

            return RedirectToAction("ViewLot", new {lotId});
        }
    }
}

Auction/Views/Home/CreateLot.cshtml
@model Auction.Models.CreateLotViewModel

<h2>Create new lot</h2>

<form method="post" asp-controller="Home" asp-action="CreateLot" enctype="multipart/form-data">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div class="row">
        <div class="form-group col-md-2">
            <label asp-for="PrimeBetPrice"></label>
            <div class="input-group">
                <input class="form-control" asp-for="PrimeBetPrice" value="0" />
                <div class="input-group-append">
                    <span class="input-group-text">$</span>
                </div>
            </div>
            <span asp-validation-for="PrimeBetPrice" class="text-danger"></span>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="FinishingDate"></label>
            <input class="form-control" asp-for="FinishingDate" maxlength="16" placeholder="Eg: 01.01.2021 12:01"/>
            <span asp-validation-for="FinishingDate" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="Coin.Images"></label>
            <div class="custom-file">
                <label class="custom-file-label" value="Choose file..."></label>
                <input asp-for="Coin.Images" class="custom-file-input"  multiple/>
            </div>
        </div>    
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea class="form-control" asp-for="Description"></textarea>
        <span asp-validation-for="Description"></span>
    </div>
    <div class="form-group">
        <label asp-for="Coin.Name"></label>
        <input class="form-control" asp-for="Coin.Name" />
        <span asp-validation-for="Coin.Name" class="text-danger"></span>
    </div>
    <div class="row">
        <div class="form-group col-md-4">
            <label asp-for="Coin.Metal"></label>
            <select class="form-control" asp-for="Coin.Metal" asp-items="@ViewBag.Metals"></select>
            <span asp-validation-for="Coin.Metal" class="text-danger"></span>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="Coin.Country"></label>
            <input class="form-control" asp-for="Coin.Country" />
            <span asp-validation-for="Coin.Country" class="text-danger"></span>
        </div>
        <div class="form-group col-md-2">
            <label asp-for="Coin.Weight"></label>
            <input class="form-control" asp-for="Coin.Weight" />
            <span asp-validation-for="Coin.Weight" class="text-danger"></span>
        </div>    
        <div class="form-group col-md-2">
            <label asp-for="Coin.Year"></label>
            <input class="form-control" asp-for="Coin.Year" />
            <span asp-validation-for="Coin.Year" class="text-danger"></span>
        </div>
    </div>
    <div>
        <input class="btn btn-primary" type="submit" value="Create" />
    </div>
</form>

@section Scripts
{
    <script>
    $(document).ready(function (){
        $(".custom-file-input").on("change", function (){
            var fileLabel = $(this).prev(".custom-file-label");
            var files = $(this)[0].files;
            if (files.length > 1){
                fileLabel.html(files.length + " files selected");
            }
            else if (files.length == 1){
                fileLabel.html(files[0].name);
            }
        });
    });
    </script>
}

Auction/Views/Home/EditLot.cshtml
@model Auction.Models.EditLotViewModel

<h2>Edit lot</h2>

<form method="post" asp-controller="Home" asp-action="EditLot" enctype="multipart/form-data" 
      asp-route-lotId="@ViewBag.lotId">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="row">
        <div class="form-group col-md-6">
            <label asp-for="Name"></label>
            <input class="form-control" asp-for="Name" value="@Model.Name"/>
            <span asp-validation-for="Name"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="Coin.Images">Reset images</label>
            <div class="custom-file">
                <label class="custom-file-label" value="Choose file..."></label>
                <input asp-for="Coin.Images" class="custom-file-input"  multiple/>
            </div>
        </div>    
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea class="form-control" asp-for="Description"></textarea>
        <span asp-validation-for="Description"></span>
    </div>
    <div class="form-group">
        <label asp-for="Coin.Name"></label>
        <input class="form-control" asp-for="Coin.Name" value="@Model.Coin.Name"/>
        <span asp-validation-for="Coin.Name" class="text-danger"></span>
    </div>
    <div class="row">
        <div class="form-group col-md-4">
            <label asp-for="Coin.Metal"></label>
            <select class="form-control" asp-for="Coin.Metal" asp-items="@ViewBag.Metals"></select>
            <span asp-validation-for="Coin.Metal" class="text-danger"></span>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="Coin.Country"></label>
            <input class="form-control" asp-for="Coin.Country" value="@Model.Coin.Country"/>
            <span asp-validation-for="Coin.Country" class="text-danger"></span>
        </div>
        <div class="form-group col-md-2">
            <label asp-for="Coin.Weight"></label>
            <input class="form-control" asp-for="Coin.Weight" value="@Model.Coin.Weight"/>
            <span asp-validation-for="Coin.Weight" class="text-danger"></span>
        </div>    
        <div class="form-group col-md-2">
            <label asp-for="Coin.Year"></label>
            <input class="form-control" asp-for="Coin.Year" value="@Model.Coin.Year"/>
            <span asp-validation-for="Coin.Year" class="text-danger"></span>
        </div>
    </div>
    <div>
        <input class="btn btn-primary" type="submit" value="Save changes" />
    </div>
</form>

@section Scripts
{
    <script>
    $(document).ready(function (){
        $(".custom-file-input").on("change", function (){
            var fileLabel = $(this).prev(".custom-file-label");
            var files = $(this)[0].files;
            if (files.length > 1){
                fileLabel.html(files.length + " files selected");
            }
            else if (files.length == 1){
                fileLabel.html(files[0].name);
            }
        });
    });
    </script>
}

Auction/Views/Home/Index.cshtml
@model IEnumerable<Auction.Models.LotViewModel>

@{
    ViewData["Title"] = "Home Page";
}
<div class="container">
    <div class="text-center">
        <h1 class="display-4">Coin Auction</h1>
        <h3>platform for the sale of antique coins</h3>
    </div>
    @foreach (var lot in Model)
    {
        <div class="row p-4 ml-5 mr-5 mt-2 position-relative" style="border: 1px solid #ececec">
            <div class="l-col-4">
                @if (lot.Coin.Images is { })
                {
                    <img src="@lot.Coin.Images.First()" style="max-height: 120px; max-width: 300px; min-width: 212px; border-radius: 5%; overflow: hidden; object-fit:cover;" alt="Image">
                }
            </div>
            <div class="col-5 position-static ">
                <a class="stretched-link" asp-controller="Home" asp-action="ViewLot" asp-route-lotId="@lot.LotId"><h4>@lot.Name</h4></a>
                <p>@lot.FinishingDate</p>
                <h4>@lot.ActualBetPrice $</h4>
            </div>
            <div class="col-3">
                <h4>@lot.UserName</h4>
            </div>
        </div> 
    }
</div>

Auction/Views/Home/LotSuccessfullyDeleted.cshtml
<h1>Lot was succesfully deleted.</h1>

Auction/Views/Home/NonActiveLot.cshtml
@model dynamic

<h1>
    This lot is non-active.
</h1>

Auction/Views/Home/ViewLot.cshtml
@using Microsoft.AspNetCore.Identity
@using Auction.DAL.Entities
@using Auction.Infrastructure
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
@model Auction.Models.LotViewModel

<div class="container">
    <div class="row">
        <h1>@Model.Name</h1>
    </div>
    <div class="row mt-2" style="min-height: 72px; border: 1px solid #ececec">
        @if (Model.Bets.Any())
        {
            <div class="col-3">Last Bet: 
                <h4>@Model.ActualBetPrice $</h4>
            </div>
            <div class="col-5">Count of bets: 
                <h4>@Model.Bets.Count</h4>
            </div>
        }
        else{
            <div class="col-3">Last Bet: 
                <h4>@Model.PrimeBetPrice</h4>
            </div>
            <div class="col-5">Count of bets: 
                <h4>@Model.Bets.Count</h4>
            </div>
        }
        <div class="col-4">Owner: 
            <a asp-controller="Account" asp-action="ViewProfile" asp-route-id="@Model.UserName"><h4>@Model.UserName</h4></a>
        </div>
    </div>
    <div class="row pt-4">
        <div class="col-5">
            @if (Model.Coin.Images is {})
            {
                <div class="fotorama">
                        @foreach (string path in Model.Coin.Images)
                        {
                            <img src="@path" alt="Image" style="max-height: 500px"/>
                        }
                </div>        
            }
        </div>
        <div class="col-7 pt-4" >
            <div class="container p-2" style="background: #f7f9f9">
                
            <div class="row">
                <div class="col-6">Started with: @Model.PrimeBetPrice $</div>
                @if (@Model.Bets.Any())
                {
                    <div class="col-6" >Actual bet:
                        <div style="font-size: 20px; color: #1c7430">@Model.ActualBetPrice $</div>
                    </div>
                }
                else
                {
                    <div class="col-6" style="font-size: 20px">Actual bet: There are no bets yet</div>
                }

            </div>
            <div class="row">
                <div class="col-6" id="time">Finish data: @Model.FinishingDate.ToString("g") </div>
                @if (Model.IsActive)
                {
                    <div class="col-6 pt-2" style="font-size: 18px; font-weight: bold" id="time-left">Time left</div>
                }
                else
                {
                    <div class="col-6" style="font-size: 18px; font-weight: bold" id="time-left">Lot finished.</div>
                }
            </div>
            @if (SignInManager.IsSignedIn(User) && UserManager.GetUserId(this.User) != ViewBag.OwnerId
                 && @Model.IsActive)
            {
                <form method="post" id="set-bet" asp-controller="Bet" asp-action="CreateBet" asp-route-lotId="@Model.LotId">
                    <div class="form-group pt-4">
                        <label>Place bet</label>
                        <div class="input-group">
                            <input id="bet-input" class="form-control" name="sum" value="@Model.ActualBetPrice"/>
                            <div class="input-group-append">
                                <span class="input-group-text">$</span>
                            </div>
                        </div>
                        <span asp-validation-for="PrimeBetPrice" class="text-danger"></span>
                    </div>
                    <div>
                        <input id="bet-button" class="btn badge-warning" type="submit" style="background: #ddff1f" value="Set bet"/>
                    </div>
                </form>
            }
            else if(UserManager.GetUserId(this.User) == ViewBag.OwnerId && @Model.IsActive)
            {
                <div class="row pt-2">
                    <div class="col-6">
                        <a class="btn btn-primary" type="button" asp-controller="Home" asp-action="EditLot" asp-route-lotId="@Model.LotId">Edit lot</a>
                    </div>                    
                    <div class="col-6">
                        <form method="post" asp-controller="Home" asp-action="DeleteLot" asp-route-lotId="@Model.LotId">
                            <input type="submit" class="btn badge-danger" value="Delete lot"/>
                        </form>
                    </div>
                </div>
            }
            else if (!Model.IsActive && Model.Bets.Last().UserId == UserManager.GetUserId(this.User))
            {
                <h4 class="text-center text-success mt-2">You won the lot. The owner's phone for connection: @Model.Phone</h4>
            }
            else if(Model.IsActive && !SignInManager.IsSignedIn(User))
            {
                <h3 class="pt-2"><a asp-controller="Account" asp-action="Login" asp-route-returnUrl=@ViewContext.HttpContext.Request.GetPathAndQuery()>Log In</a> to take part in auction</h3>
            }
            </div>
        </div>
    </div>
    <span class="row mt-4">
        <div class="col">
            <h4>Description</h4>
            <p>@Model.Description</p>
        </div>
    </span>
    <div class="row mt-2">
        <table class="table">
            <tbody>
            <tr>
                <th scope="row">
                    Country
                </th>
                <td>
                    @Model.Coin.Country
                </td>
            </tr>
            <tr>
                <th scope="row">
                    Year
                </th>
                <td>
                    @Model.Coin.Year
                </td>    
            </tr>    
            <tr>
                <th scope="row">
                    Material
                </th>    
                <td>
                    @Model.Coin.Metal
                </td> 
            </tr>        
            <tr>
                <th scope="row">
                    Weight, gr.
                </th>     
                <td>
                    @Model.Coin.Weight
                </td>                  
            </tr>
            </tbody>
        </table>
    </div>
</div>

@section Scripts
{
    <script>
    let interval = (finishDate) => {
        let finishTimeInISO = new Date(Date.parse(finishDate));
        timeUpdateManager(finishTimeInISO);
        let currentTime = new Date();
        return finishTimeInISO - currentTime;
    }
    
    let update = () => {  
      let difference = new Date(interval('@Model.FinishingDate.ToString("O")'));
      
      let month = difference.getUTCMonth().toString().concat(" month(s) ");
      let day = (difference.getDate() - 1).toString().concat(" day(s) ");
      let hours = difference.getUTCHours() > 9 ? difference.getUTCHours().toString() : "0".concat(difference.getUTCHours().toString());
      hours = hours.concat(':');
      let minutes = difference.getMinutes() > 9 ? difference.getUTCMinutes().toString() : "0".concat(difference.getUTCMinutes().toString());
      minutes = minutes.concat(':');
      let seconds = difference.getSeconds() > 9 ? difference.getUTCSeconds().toString() : "0".concat(difference.getUTCSeconds().toString());
      
      let fullDifference = month + day + hours + minutes + seconds;
      
      document.getElementById("time-left").innerText = timerId == null ? "Lot finished"
       : fullDifference.toString();
    }
        
    let timerId;
    
    let clockStart = () => {
         timerId = setInterval(update, 1000);
         update();
    }    
    
    let clockStop = () => {
        clearInterval(timerId);
        timerId = null;
        }
        
    let timeUpdateManager = (time) => {        
        if (time.getTime() <= new Date().getTime()){
            clockStop();
        }
    }
    
    clockStart();
    </script>
}